version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:17"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      bun-development-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:31"
      timezone: Europe/Stockholm
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
